spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: streamingdatabase
      username: rootuser
      password: rootpass
      authentication-database: admin

  servlet:
    request:
      multipart:
        max-file-size: 25MB
        max-request-size: 25MB
        enabled: true


