spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: streamingdatabase
      username: rootuser
      password: rootpass
      authentication-database: admin

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always